import { expect, test } from '@playwright/test';
import { isApprovedStagingTarget } from '@unit-talk/db';
import { writeFile } from 'node:fs/promises';
import path from 'node:path';

test('ordinary operator sign-in persists settlement, immutable correction, attribution and Track Only containment', async ({ page }, testInfo) => {
  expect(isApprovedStagingTarget(process.env.SUPABASE_URL)).toBe(true);
  const pickId = process.env.CC_STAGING_PICK_ID;
  expect(pickId).toBeTruthy();
  const errors: string[] = [];
  page.on('pageerror', (error) => errors.push(error.message));
  const read = async (table: string, params: Record<string, string>) => {
    const response = await fetch(`${process.env.SUPABASE_URL}/rest/v1/${table}?${new URLSearchParams(params)}`, { headers: { apikey: process.env.SUPABASE_SERVICE_ROLE_KEY!, Authorization: `Bearer ${process.env.SUPABASE_SERVICE_ROLE_KEY}` } });
    expect(response.ok, `independent ${table} read`).toBe(true);
    return await response.json() as Array<Record<string, unknown>>;
  };
  await page.goto(`/picks/${pickId}`);
  await page.getByLabel('Username', { exact: true }).fill(process.env.COMMAND_CENTER_AUTH_USERNAME!);
  await page.getByLabel('Password', { exact: true }).fill(process.env.COMMAND_CENTER_AUTH_PASSWORD!);
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await expect(page.getByTestId('operator-identity')).toContainText('staging-proof-operator');
  await page.getByRole('button', { name: 'Win', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Settle Pick', exact: true })).toBeDisabled();
  await page.locator('#settle-outcome-basis').fill('Synthetic staging result observed for browser settlement proof');
  await page.locator('#settle-result-source-url').fill('https://example.invalid/utv2-1950/original');
  await page.locator('#settle-observed-at').fill(new Date().toISOString());
  await page.getByRole('button', { name: 'Settle Pick', exact: true }).click();
  await page.getByRole('button', { name: 'Confirm', exact: true }).click();
  await expect(page.getByText('Settlement recorded.', { exact: true }).or(page.getByRole('heading', { name: 'Correct Settlement', exact: true })).first()).toBeVisible();
  const [original] = await read('settlement_records', { select: '*', pick_id: `eq.${pickId}` });
  expect(original?.result).toBe('win');
  expect(original?.settled_by).toBe('staging-proof-operator');
  expect(original?.corrects_id).toBeNull();
  await page.reload();
  await expect(page.getByRole('heading', { name: 'Correct Settlement', exact: true })).toBeVisible();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole('button', { name: 'Loss', exact: true }).click();
  await page.locator('#correct-outcome-basis').fill('Synthetic staging scoring correction; original win was incorrect');
  await page.locator('#correct-result-source-url').fill('https://example.invalid/utv2-1950/correction');
  await page.locator('#correct-observed-at').fill(new Date().toISOString());
  await page.getByRole('button', { name: 'Submit Correction', exact: true }).click();
  await page.getByRole('button', { name: 'Confirm', exact: true }).click();
  await expect(page.getByText('Correction recorded.', { exact: true })).toBeVisible();
  const history = await read('settlement_records', { select: '*', pick_id: `eq.${pickId}` });
  expect(history).toHaveLength(2);
  expect(history.find((row) => row.id === original!.id)).toEqual(original);
  const correction = history.find((row) => row.id !== original!.id)!;
  expect(correction.corrects_id).toBe(original!.id);
  expect(correction.result).toBe('loss');
  expect(correction.settled_by).toBe('staging-proof-operator');
  expect(correction.evidence_ref).not.toBe(original!.evidence_ref);
  const [pick] = await read('picks', { select: 'id,status', id: `eq.${pickId}` });
  expect(pick?.status).toBe('validated');
  expect(await read('distribution_outbox', { select: 'id', pick_id: `eq.${pickId}` })).toEqual([]);
  expect(await read('pick_lifecycle', { select: 'to_state', pick_id: `eq.${pickId}`, to_state: 'eq.settled' })).toEqual([]);
  const audits = await read('audit_log', { select: 'id,actor,entity_id,action', entity_ref: `eq.${pickId}` });
  expect(audits.some((row) => row.entity_id === original!.id && row.actor === 'staging-proof-operator')).toBe(true);
  expect(audits.some((row) => row.entity_id === correction.id && row.actor === 'staging-proof-operator')).toBe(true);
  await page.reload();
  await expect(page.getByTestId('settlement-recap')).toContainText('Not applicable');
  expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);
  expect(errors).toEqual([]);
  await page.screenshot({ path: testInfo.outputPath('corrected-pick-phone.png'), fullPage: true });
  await writeFile(path.join(process.env.CC_STAGING_PROOF_OUTPUT!, 'operator-write-proof.json'), JSON.stringify({ pickId, originalSettlementId: original!.id, correctionSettlementId: correction.id, actor: correction.settled_by, originalPreserved: true, lifecycle: pick?.status, outboxRows: 0, auditRows: audits.length }, null, 2));
});
