/** Render a refusal with a usable credential form, without executing protected pages. */
export function signInDocument(nonce: string, unavailable: boolean, basicAvailable = true): string {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Sign in — Command Center</title>
<style nonce="${nonce}">*{box-sizing:border-box}body{margin:0;min-height:100vh;display:grid;place-items:center;padding:24px;background:#0b1220;color:#e5edf8;font:16px system-ui,sans-serif}main{width:100%;max-width:420px;padding:32px;border:1px solid #34425a;border-radius:16px;background:#121e30}h1{font-size:26px;margin:8px 0 12px}p{color:#acbdd3;line-height:1.5}label{display:block;margin:18px 0 6px}input,button{width:100%;padding:12px;border-radius:8px;font:inherit}input{border:1px solid #61728e;background:#0b1220;color:#fff}button{margin-top:24px;border:0;background:#5194ff;color:#08111f;font-weight:650;cursor:pointer}button:disabled{opacity:.6}input:focus,button:focus{outline:3px solid #97baff;outline-offset:3px}#error{color:#ffb9b9}small{color:#acbdd3}a{color:#97baff}</style></head><body><main>
<small>UNIT TALK · INTERNAL OPERATIONS</small><h1>${unavailable ? 'Sign-in unavailable' : 'Sign in to Command Center'}</h1>
${unavailable ? '<p>Operator access is not configured correctly. Contact the system administrator. Your data has not been loaded.</p>' : `<p>Use your operator credentials to continue to the page you opened.</p>
<form id="sign-in">${basicAvailable ? '<label for="username">Username</label><input id="username" name="username" autocomplete="username" required autofocus maxlength="256"><label for="password">Password</label><input id="password" name="password" type="password" autocomplete="current-password" required maxlength="1024">' : '<label for="token">Operator access token</label><input id="token" name="token" type="password" autocomplete="off" required autofocus maxlength="4096">'}<button type="submit">Sign in</button><p id="error" role="alert" aria-live="polite"></p></form><noscript><p>Enable JavaScript to sign in.</p></noscript>
<script nonce="${nonce}">document.getElementById('sign-in').addEventListener('submit',async function(event){event.preventDefault();const button=this.querySelector('button');const error=document.getElementById('error');error.textContent='';button.disabled=true;button.textContent='Signing in…';try{let authorization;if(this.elements.token){authorization='Bearer '+this.elements.token.value;}else{const username=this.elements.username.value;const password=this.elements.password.value;const bytes=new TextEncoder().encode(username+':'+password);let binary='';for(const byte of bytes)binary+=String.fromCharCode(byte);authorization='Basic '+btoa(binary);}const response=await fetch('/api/session',{method:'POST',credentials:'same-origin',headers:{Authorization:authorization}});if(this.elements.password)this.elements.password.value='';if(this.elements.token)this.elements.token.value='';if(!response.ok){error.textContent=response.status===401?'Credentials were not accepted. Try again.':'Sign-in is temporarily unavailable. Please try again.';return;}window.location.reload();}catch{error.textContent='Cannot reach Command Center. Check your connection and try again.';}finally{button.disabled=false;button.textContent='Sign in';}});</script>`}
</main></body></html>`;
}
