-- MIGRATION-HISTORY-RECEIPT v1
-- UTV2-1822: non-executable historical version receipt.
--
-- receipt_version:     1
-- remote_version:      202604210005
-- remote_name:         utv2_703_wnba_period_half_market_types
-- source_kind:         ledger_payload
-- source_path:         supabase/migrations_archive/ledger/202604210005_utv2_703_wnba_period_half_market_types.sql
-- source_sha256:       9e2af9bef78c2aa1493c95d449f345b88a95e5a4a6d0df53f55d11b7cbaf7c35
-- archive_intent_path: supabase/migrations_archive/202604210005_utv2_703_wnba_period_half_market_types.sql
-- archive_diverges:    true
-- subsumed_by:         supabase/migrations/00000000000000_baseline_live_schema.sql
--
-- WHY THIS FILE CONTAINS NO EXECUTABLE SQL
--
-- This version is recorded as applied in the remote migration ledger, so
-- `supabase db push` refuses to run at all while it has no local counterpart
-- (pkg/migration/apply.go: "Remote migration versions not found in local
-- migrations directory"). That precondition is about CORRESPONDENCE, not about
-- re-execution: the CLI requires a local file to exist for every remote row.
--
-- Its schema effects are already contained in the active baseline snapshot
-- (supabase/migrations/00000000000000_baseline_live_schema.sql),
-- which is the replay root. Re-executing this migration would therefore either
-- duplicate objects the baseline already creates or replay data statements
-- against a database that has already absorbed them. Neither is correct, so
-- this file asserts identity and provenance only and executes nothing.
--
-- The exact SQL that actually executed is preserved verbatim, outside the
-- active replay path, at source_path above, and is bound here by
-- source_sha256. scripts/ci/migration-history-receipt-validator.ts enforces
-- that binding and rejects any executable statement added to this file.
--
-- DIVERGENCE NOTICE
--
-- The repository archive file at archive_intent_path differs from what this
-- version actually executed. The ledger payload is executed-history truth and
-- is what source_sha256 binds. The archive file is retained unchanged as
-- later-edited intent/provenance. The two are deliberately NOT reconciled.
