-- MIGRATION-HISTORY-RECEIPT v1
-- UTV2-1822: non-executable historical version receipt.
--
-- receipt_version:     1
-- remote_version:      202605030002
-- remote_name:         <null>
-- source_kind:         archive_fallback
-- source_path:         supabase/migrations_archive/202605030002_utv2_772_provider_offer_line_snapshots.sql
-- source_sha256:       99713abd7a3df91d4ebfb06ca35bc18e785f7b1cc177864d48ca1dc97929e0a6
-- subsumed_by:         supabase/migrations/00000000000000_baseline_live_schema.sql
--
-- WHY THIS FILE CONTAINS NO EXECUTABLE SQL
--
-- This version is recorded as applied in the remote migration ledger, so
-- `supabase db push` refuses to run at all while it has no local counterpart
-- (pkg/migration/apply.go: "Remote migration versions not found in local
-- migrations directory"). That precondition is about CORRESPONDENCE, not about
-- re-execution: the CLI requires a local file to exist for every remote row.
--
-- Its schema effects are already contained in the active baseline snapshot
-- (supabase/migrations/00000000000000_baseline_live_schema.sql),
-- which is the replay root. Re-executing this migration would therefore either
-- duplicate objects the baseline already creates or replay data statements
-- against a database that has already absorbed them. Neither is correct, so
-- this file asserts identity and provenance only and executes nothing.
--
-- The exact SQL that actually executed is preserved verbatim, outside the
-- active replay path, at source_path above, and is bound here by
-- source_sha256. scripts/ci/migration-history-receipt-validator.ts enforces
-- that binding and rejects any executable statement added to this file.
